; Project Euler - Problem 002
; https://projecteuler.net/problem=2

; Each new term in the Fibonacci sequence is generated by adding the
; previous two terms. By starting with 1 and 2, the first 10 terms will be:
;
; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;
; By considering the terms in the Fibonacci sequence whose values do not
; exceed four million, find the sum of the even-valued terms.

(ns euler.problem-002)

(defn problem-002
  "Sum even fibonacci numbers"
  [limit]
  (reduce +
    (loop [fib1 1
           fib2 2
           fibs []]
      (if (>= fib1 limit)
        fibs
        (let [new-fib1 fib2
              new-fib2 (+ fib1 fib2)]
          (if (= 0 (mod fib1 2))
            (recur new-fib1 new-fib2 (conj fibs fib1))
            (recur new-fib1 new-fib2 fibs)))))))
